### ISSUE TITLE
timer limitation

### ISSUE THREAD

**Issue by jodinathan** [renatoathaydes/structured_async#1]
In the readme it says there are limitations regarding timers.  
What about creating a timer-like class that work ok with the cancellable future?  
does it make sense? :)

**Comment by renatoathaydes** [comment]
Dart timers work ok with structured_async currently, the "limitation" (i.e. waking up timers early) is by design so that there's less chance of futures hanging forever because a timer never woke up again.

Can you explain better what you would expect a "custom" timer to provide differently?
